// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	repo "echo_template/domain/repo"

	mock "github.com/stretchr/testify/mock"
)

// TxFn is an autogenerated mock type for the TxFn type
type TxFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *TxFn) Execute(_a0 *repo.TX) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*repo.TX) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTxFn creates a new instance of TxFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxFn {
	mock := &TxFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
