// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"

	uploader "github.com/cloudinary/cloudinary-go/v2/api/uploader"
)

// FileCloudService is an autogenerated mock type for the FileCloudService type
type FileCloudService struct {
	mock.Mock
}

// Update provides a mock function with given fields: ctx, file
func (_m *FileCloudService) Update(ctx context.Context, file *multipart.FileHeader) (*uploader.UploadResult, error) {
	ret := _m.Called(ctx, file)

	var r0 *uploader.UploadResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) (*uploader.UploadResult, error)); ok {
		return rf(ctx, file)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) *uploader.UploadResult); ok {
		r0 = rf(ctx, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uploader.UploadResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader) error); ok {
		r1 = rf(ctx, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFileCloudService creates a new instance of FileCloudService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileCloudService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileCloudService {
	mock := &FileCloudService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
