// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"
	model "trial_backend/domain/repo/model"

	mock "github.com/stretchr/testify/mock"

	request "trial_backend/presenter/request"
)

// PostService is an autogenerated mock type for the PostService type
type PostService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *PostService) Create(ctx context.Context, req request.CreatePostRequest) (*model.Post, error) {
	ret := _m.Called(ctx, req)

	var r0 *model.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.CreatePostRequest) (*model.Post, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.CreatePostRequest) *model.Post); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.CreatePostRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, req
func (_m *PostService) Delete(ctx context.Context, req request.DeletePostRequest) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, request.DeletePostRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetList provides a mock function with given fields: ctx, req
func (_m *PostService) GetList(ctx context.Context, req request.GetListPostRequest) ([]*model.Post, *int64, error) {
	ret := _m.Called(ctx, req)

	var r0 []*model.Post
	var r1 *int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, request.GetListPostRequest) ([]*model.Post, *int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.GetListPostRequest) []*model.Post); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.GetListPostRequest) *int64); ok {
		r1 = rf(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*int64)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, request.GetListPostRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetOne provides a mock function with given fields: ctx, id
func (_m *PostService) GetOne(ctx context.Context, id string) (*model.Post, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Post, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Post); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, req
func (_m *PostService) Update(ctx context.Context, req request.UpdatePostRequest) (*model.Post, error) {
	ret := _m.Called(ctx, req)

	var r0 *model.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.UpdatePostRequest) (*model.Post, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.UpdatePostRequest) *model.Post); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.UpdatePostRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPostService creates a new instance of PostService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostService {
	mock := &PostService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
